### ISSUE TITLE
strange matrix subtraction errors

### ISSUE THREAD

**Issue by ribrdb** [davidedc/Algebrite#102]
If I do `[[0,0],[1,1]]-[[0,0],[1,1]]` I get an error:
```
Stop: Cannot promote tensor due to inconsistent tensor components.
```
However it seems to work fine if any of the zeros is changed. For example:`[[0,0*1],[1,1]]-[[0+0,0],[1,1]]` returns `[[0,0],[0,0]]`

Also subtracting a matrix that is all zeros returns the number zero instead of a matrix: `zero(2,2)-zero(2,2)`

**Comment by davidedc** [comment]
the problem appears to be in yymultiply, in

```
  # is either operand zero?
  if (isZeroAtomOrTensor(p1) || isZeroAtomOrTensor(p2))
    if evaluatingAsFloats then push_double(0.0) else push(zero)
    return
```

basically -[0,0] is -1*([0,0]), which incorrectly becomes 0.

will work on a fix.

**Comment by davidedc** [comment]
fixed in https://github.com/davidedc/Algebrite/commit/2f54ab82e1735ca99b2ee7f1602882b6e2fc9dbf . Feel free to re-open the issue if you see further problems.
