### ISSUE TITLE
generating formula for RX and Tx exchange between two different equipment not speaking same language 

### ISSUE THREAD

**Issue by yboujraf** [davidedc/Algebrite#104]
Dear @antimatter15 , @ribrdb  , @waywardmonkeys , @laughinghan  , @davidedc 

I hope you are well and my best wishes for 2020,

I have an issue too #https://github.com/josdejong/mathjs/issues/1699

And maybe you could help me with your library.

### Topic - translate from different protocols data by generating mathematic formula.

One of the properties is "Formulas" of our datamodel is 

### Formulas ( Rx / Tx)

•	Formulas provide a way to project values received from an equipment to another value range or representation.
•	For example, an equipment might send gain values as INTEGERs ranging from 0 to 65535, while the actual gain range in is -64db to 12db. Obviously, the user of a front-end application prefers to deal with the gain values in db instead of the technical INTEGER range.
•	To accommodate for this need, I am looking to provides the concept of formulas.
 
•	This will create a basic formula which does not alter the input value – meaning it returns the identity of the input value:

![image](https://user-images.githubusercontent.com/6151258/71525560-7a667680-28d2-11ea-8958-cb7b48afbc4c.png)

Picture from ww.lawo.de
 
•	The input value of the formula is denoted with the symbol $. You can use this symbol in an arithmetic expression which yields the desired output range.
•	The line “$ =“ defines the input value (as sent by the device) of the formula.
•	The following line “RX($) =“ defines the expression used to convert values that have been received from the device.
•	The following line “TX($) =” defines the expression used to convert values that are about to get sent to the device. This expression has to reverse the projection made in the RX expression.

•	To follow the ifSpeed example, let’s display the speed of the interface in megabytes per second instead of bits per second:
o	Enter a test input value in the “$ =” field, e.g. “10000000” (10 megabit)
o	Enter the expression $ / 8000000.0 into the “RX” field. 8000000 is the factor used to turn unit bits into unit megabyte.
o	To reverse the RX expression, enter the expression $ * 8000000.0 into the “TX” field.
o	You will now see the following:

![image](https://user-images.githubusercontent.com/6151258/71525777-93bbf280-28d3-11ea-9b69-f0cf4ecae74b.png)

Picture from www.lawo.de

o	You can see that the result of the RX expression is 1.25 (megabytes) and the result of the TX expression, which uses 1.25 as input value, is 10000000 (bits per second, which is equal to the input value of the RX expression).

### INPUT RANGE

•	I have an Analog to Digital convert 12 bits (4096 positions)
•	The manufacturer of the A/D converter infor you for 0 = -128dB and for 4095 = +15 dB

I am looking to create as above "Formula" with possibility to select linear or log the Rx and Tx formula.

### Data model of my paramater

```
{
                    "identifier": "ParameTypeStream",
                    "description": "Stream PPM MAIN",
                    "value": 0,
                    "minimum": -4096,
                    "maximum": 480,
                    "access": "read",
                    "format": "%8.2f°",
                    "enumeration": "",
                    "factor": 32,
                    "isOnline": true,
                    "default": -1024,
                    "type": "integer",
                     "formula": "1000*\n1000/"
                }
 ```

**The properties : formula**

The Minimum & Maximum are :

 ```                 
"minimum": -4096,
"maximum": 480,
```

Then I need to generate the correct formula for Rx & Tx.

Regarding **formula "1000*\n1000/"**

That means when the client receives this properties the "/n" is the separation from RX formula then TX formula then no needs two properties 

Here :

RX = value *1000
TX = value /1000

### Use case - write the formula - RX

1. the client introduces the formula in an editbox. Just the '$' indicates the value I need to passing into the math expression and get the result.

### Use case - write the formula - TX

If the RX formula is already written in the editbox , I need and expect with Mathjs library to generate the invert formula for TX and vice-versa if Tx is filled, then I got RX.

```
If RX = $/1000
then I need to get for TX = $*1000
```

The formula could be complex (log, square, ^, (expression)*log) I attached a document from my friend written for F# (Microsoft) long time ago and now we are using nodejs and javascript.

[Ember+ Formulas.pdf](https://github.com/josdejong/mathjs/files/4007889/Ember%2B.Formulas.pdf)

I hope you could make a simple example of code how to use it and then I will try it ;-)

Best Wishes for 2020
Youssef

**Comment by davidedc** [comment]
Hi Youssef,

the part related to units of measures can be addressed by Algebrite, that should be no problem, see examples on the home page.

I skipped the considerations of logarithmic scales, I'd have to look better.

However the tricky bit here is formula inversion. Algebrite can solve polynomial equations (which would work in the example you write), but I see from the examples that you need more...

It seems from the inversion examples in the .pdf that you require the engine to figure out a lot about the domain/co-domain, also the third example is non-trivial, in fact I'd say it's not invertible, I couldn't get wolfram alpha to give an expression for it, see [this](https://www.wolframalpha.com/input/?i=InverseFunction%5B+x+-+Log%28x+%2F+%28e%5E%28-x%29+*+x%5Esin%281+%2F+x%29%29%29%5D&assumption=%7B%22C%22%2C+%22InverseFunction%22%7D+-%3E+%7B%22SolveWord%22%7D&assumption=%7B%22FunClash%22%2C+%22Log%22%7D+-%3E+%7B%22Log10%22%7D).

In fact, in general, most functions are really not invertible unless you pick specific domains, assumptions, restrictions etc.

So some parts are easy, some parts are tough, that's all I can say. If you need more support you can contact me at my email - see my profile.

Closing as this is not an "open" issue, the others mentioned can still add comments as they see fit.

Cheers!

**Comment by davidedc** [comment]
P.S. I see from https://github.com/josdejong/mathjs/issues/1699 that the automatic inversion is a "nice to have".

Then yes Algebrite can do the parsing (just replace "$" with "x") and units of measure. So you should be good.

All the best!

**Comment by yboujraf** [comment]
Dear @davidedc 

May I ask you to share a sample of code with the use cases ?

RX = log(X)
and the Alebrite reverse the RX expression by Tx = exp(X) ?

To confirm it will work, I need to have :

The two expressions must have the following mathematical relationship: expr2(expr1(x)) = x = expr1(expr2(x))

This means, expr2 must inverse the projection applied by expr1 and vice versa, like in these examples:

expr1 = $ / 2
expr2 = $ * 2

expr1 = exp($)
expr2 = log($)

Best Regards
Youssef

**Comment by davidedc** [comment]
Hi Youssef,

I can provide a quick sketch for the simple example. The exp-log example is not going to work because Algebrite can only find solutions to polynomials.

So, you take the expr1 and transform it (using regex) to

y = x/2

which really means:

x/2 - y

then you do

roots(x/2 - y,x)

and you get

2*y

then you can transform that (using regex, y -> $) to

2*$

That's the outline, good luck!

**Comment by yboujraf** [comment]
Dear @davidedc 

Will try and let you know.

Best Regards,
Youssef
