### ISSUE TITLE
missing minuses when printing numbers in terms (when printing non-normalised terms)

### ISSUE THREAD

**Issue by ribrdb** [davidedc/Algebrite#106]
`sum(k*(-3),k,0,x)` returns `sum(k*3,k,0,x)`

**Comment by davidedc** [comment]
this is a printing error. When it comes to print the second factor (-3), it does:

```
print_factor = (p, omitParens) ->
  # debugger
  accumulator = ""
  if (isNumericAtom(p))
    accumulator += print_number(p, false)
```

and that
```
print_number(p, false)
```

just prints "3"

Unfortunately just changing that flag doesn't work, I need to figure out again the deeper logic of when and why minus signs are omitted.

Another option (maybe) is to evaluate the body of the summation even when the indexes are undefined, this would cause the body to take a better canonical form, and to not cause the problem in the first place.

Maybe both things should be investigated/done

**Comment by davidedc** [comment]
the smallest example of this bug is:

```Algebrite.run('quote(k*(-2))');```

which returns ```k*2``` instead of ```k*(-2)```
