### ISSUE TITLE
1 - 1/2*0^2 results in divide by zero error

### ISSUE THREAD

**Issue by derivitaandrew** [davidedc/Algebrite#121]
Expressions of the form `something - frac*0^exp` cause the divide by zero error.

For example
```
1 - 1/2*0^2
Stop: divide by zero
```

It seems that the subtraction, fraction that doesn't simplify to an integer, and 0 are all required to see the bug.

---
#### Some test cases
Cause the error:
```
1. 1 - 1/2*0^2
2. 1 - 3/2*0^2
3. 1 - 1/2*0^1
```
![image](https://user-images.githubusercontent.com/67478079/90469496-2fee7000-e0d6-11ea-8525-c75e9e067686.png)

Similar, but no error:
```
4. 1 - 1/2*-0^2, 
5. 1 - 1/2*5^2, 
6. 1 + 1/2*0^2, 
7. 1 + -1/2*0^2, 
8. -1/2*0^2, 
9. 1 - 1/2*0*0, 
10. 1 - 1/x*0^2, 
11. 1 - 10/2*0^2, 
12. 1 - 2*0^2, 
13. 1 - 0^2, 
14. 1 - 0^2*(1/2)
```
![image](https://user-images.githubusercontent.com/67478079/90469572-6a580d00-e0d6-11ea-97a7-bc7104b62b7d.png)

**Comment by davidedc** [comment]
here is where the problem lies. The __is_radical_number routine mistakes n^m (with N and M any numeric atoms ) as a radical, which needs fixing.

![Screenshot 2021-04-06 at 11 27 30](https://user-images.githubusercontent.com/769568/113774941-e368ab00-971f-11eb-9fe9-3b2e0a347b97.png)
