### ISSUE TITLE
Good Old Javascript

### ISSUE THREAD

**Issue by aminemarref** [davidedc/Algebrite#126]
Hello,

I would like to use Algebrite as part of an app I am developing, and NodeJS is not exactly my area of strength. How can I obtain  Algebrite as a JavaScript file that can be run in the client side in the classical way i.e. included from within an HTML/PHP file?

Many Thanks.

**Comment by jarble** [comment]
You can use [browserify](http://browserify.org/) to run node.js modules on the client-side.

**Comment by davidedc** [comment]
also other ideas:
* clone the repo where the Algebrite website lives - that will have the algebrite javascript and the sandbox
* download the JS from the sandbox (look into the html of the sandbox, you'll find where the algebrite js is pulled from)
