### ISSUE TITLE
Installation in Windows

### ISSUE THREAD

**Issue by aminemarref** [davidedc/Algebrite#127]
Hello,

The building step of the package raises an exception under Windows 10 because it complains about not finding the command "cat" [1]. This happens both in CMD and PowerShell.

Could you please provide scripts that would make the building work both under Linux and Windows?

Many Thanks.

[1] 'cat' is not recognized as an internal or external command,

**Comment by davidedc** [comment]
Hi - I'm afraid I don't have enough resources to look into this, but here are some ideas:
* install Windows Subsystem for Linux (WSL) - which is a Microsoft-maintained Linux virtual-machine that runs very well on Windows 10. I used it for very complex projects and it works great - it basically lets you work on a Linux-like system right from your normal Windows. It's excellent.
* use the Windows-equivalent command (I believe it's "type", but.a search will help you)
