### ISSUE TITLE
expand(sin(x)) fails

### ISSUE THREAD

**Issue by murkle** [davidedc/Algebrite#14]
This doesn't work:
```
Algebrite.run("expand((sin(x)+1)^2)")
"Stop: divide by zero"
```
Minimal test case:
```
Algebrite.run("expand(sin(x))")
"Stop: divide by zero"
```

**Comment by davidedc** [comment]
found the issue, gonna fix soon. Note that "expand" only does partial fraction expansion. Algebrite.run("(sin(x)+1)^2") should rather give the result you want.

**Comment by davidedc** [comment]
(I appreciate that, as per note above on how expand works, the example in the home page in misleading)
