### ISSUE TITLE
Failing to simplify 1/(x-1)+1/(1-x)

### ISSUE THREAD

**Issue by thunderkid** [davidedc/Algebrite#140]
Happy to see a new release!
In version 1.2.1, simplifying this
```1/(x-1)+1/(1-x)```
correctly gave `0`.
In version 1.4.0 it doesn't simplify at all. You can see that from the algebrite.org website or from the npm version.
(It also fails in 1.3.x.)

**Comment by davidedc** [comment]
thanks! Indeed this has been reported also in https://github.com/davidedc/Algebrite/issues/131 , as such I’m going to close this one as duplicate. Please follow the other issue for updates.
