### ISSUE TITLE
integral(arccos(x)) is wrong (missing minus sign)

### ISSUE THREAD

**Issue by murkle** [davidedc/Algebrite#15]
```
Algebrite.run("(integral(arccos(x)))")
"(-x^2 + 1)^(1/2) + x arccos(x)"
```

Should be
` -sqrt(-x² + 1) + x arccos(x) `

**Comment by davidedc** [comment]
thanks. corrected in the integral table. Gonna submit change soon.

P.S. are these bugs that you are finding part of a larger suite of tests that you could share so I make sure that the larger set doesn't ever break as well?

**Comment by murkle** [comment]
I found this one by running derivative(integral()) and vice-versa on the standard functions

I do have a big test-suite that we use for GeoGebra - I haven't tried anything from that yet though :smile: 
https://github.com/geogebra/geogebra/blob/master/web/war/__giac.js
