### ISSUE TITLE
How to solve equations?

### ISSUE THREAD

**Issue by Bellisario** [davidedc/Algebrite#164]
I'm trying to use this library to solve equations via JS, but I find really difficult because there is no explicit API use to do this, an example or something else...

**Comment by jarble** [comment]
You can do this using the `roots` function. There's an example on the [homepage](http://algebrite.org/):
```
roots(x^4 + x^3 + x^2 + x + 1) # third and fourth degree are solved too
roots(m*x^9 + n) # roots of special polynomials
roots((x^4+x^3)*(x^4*x^2)) # roots of factorable polynomials
```

**Comment by Bellisario** [comment]
Thanks! I'll close this issue,,,
