### ISSUE TITLE
sum

### ISSUE THREAD

**Issue by MayaKirillova** [davidedc/Algebrite#20]
The `sum` function is listed in the **Algebrite** [function reference](http://algebrite.org/reference.html#sum), but doesn't appear to have an implementation yet.

The function reference says:

> **sum(i,j,k,f)**
> 
> For i equals j through k evaluate f. Returns the sum of all f.

But when I execute the following code in nodejs

```
var Algebrite = require('algebrite');
Algebrite.run('sum(n,1,6,x^n)');
```

I get the error message

> 'Eval_sum is not defined'

By contrast, if I execute the same expression in **eigenmath**, I get the following results:

```
$ ./math
> sum(n,1,6,x^n)
 6    5    4    3    2
x  + x  + x  + x  + x  + x
```

My goal is to be able to evaluate even more complicated expressions such as

```
sum(k,2,12,coeff((sum(n,1,6,x^n))^2,x,k))
```

which should return 36.

Thanks!

**Comment by davidedc** [comment]
acknowledged. Will try to get on this soon.
