### ISSUE TITLE
Isone undefined in dist/algebrite.js

### ISSUE THREAD

**Issue by miketheanimal** [davidedc/Algebrite#25]
npm installed a few days ago

> var a=require('algebrite') ;
> e=a.parse('(x+1)*(x+2)')
> U {
>   cons: 
>    { car: U { cons: [Object], q: rational {}, k: 5, printname: 'multiply' },
>      cdr: U { cons: [Object], q: rational {}, k: 0 } },
>   q: rational {},
>   k: 0 }
> a.expand(e)
> ReferenceError: isone is not defined
>     at expand (/home/mike/solver/client/node_modules/algebrite/dist/algebrite.js:5756:9)
>     at expand (/home/mike/solver/client/node_modules/algebrite/dist/algebrite.js:5739:9)
>     at Eval_expand (/home/mike/solver/client/node_modules/algebrite/dist/algebrite.js:5721:12)
>     at Eval_cons (/home/mike/solver/client/node_modules/algebrite/dist/algebrite.js:5205:16)
>     at Eval (/home/mike/solver/client/node_modules/algebrite/dist/algebrite.js:5061:9)
>     at fixed_top_level_eval (/home/mike/solver/client/node_modules/algebrite/dist/algebrite.js:16620:5)
>     at exec (/home/mike/solver/client/node_modules/algebrite/dist/algebrite.js:16591:7)
>     at repl:1:3
>     at REPLServer.defaultEval (repl.js:262:27)
>     at bound (domain.js:287:14)

I cloned the repo, I notice that in algebrite.bundle-for-browser.js there is:

.... isnpi, isnum, isone, isoneover, ....

in the var list near the beggining, while in dist/algebrite.js is:

.... isnpi, isnum, isoneover, ....

ie., isone is missing

**Comment by miketheanimal** [comment]
Quick follow up: if i hand-edit dist/algebrite.js to include isone in that line and add the isone definition:

  isone = function(p) {
    return isplusone(p) || isminusone(p);
  };

then the problem disappears. A build issue maybe?

Thanks
Mike

**Comment by davidedc** [comment]
sorry for the late reply.

That's strange. The implementation of "is one" is there already. What I see is missing is the export at the end of "is.coffee".

I'll add that, but still, that should not be relevant for the example you pasted...

I'll look into this... but which version of Algebrite did npm download?

**Comment by miketheanimal** [comment]
node_modules/algebrite/package.json has 0.2.23 .. is that the right information? Unfortunately algebrite does not appear in my package.json :(

**Comment by davidedc** [comment]
of course, sorry, I need to do a publish to npm to update it to the last one... Will do as soon as I have 5 minutes tonight.

**Comment by miketheanimal** [comment]
thanks ..... and here comes another issue :)

**Comment by davidedc** [comment]
this is now working in the published version 0.4.2 . release notes here: http://algebrite.org/docs/index.html
