### ISSUE TITLE
Reusing compiled/evaluated code

### ISSUE THREAD

**Issue by danielsvane** [davidedc/Algebrite#32]
I'm trying to generate an isosurface, and right now I'm running the same expression, with replaced variables 15000+ times. Is there any way to optimize this call:

`Algebrite.eval(eq, "a", a, "b", b)`

Thanks for all your work.

**Comment by davidedc** [comment]
Hi, yes in the Zeno branch there are some JS code generation facilities. I'll have to refine and document them, but if you look for "generation" you'll find the trail.

**Comment by danielsvane** [comment]
My best bet is `findDependenciesInScript()`, which kinda generates JS code, but doesn't replace "cos", "sin" and "e^x" gets replaced with "Math.pow(exp(1), x)". For now I made a parser in nearley to get JS code I can eval, but it's not a very elegant solution.

**Comment by davidedc** [comment]
my vote goes for using/improving that code generation facility. It's a draft, true, but I'm going to keep working on it, so I'd find any improvements on that very useful, they will be included and maintained...

**Comment by danielsvane** [comment]
After updating to 1.0, the code generation works well for my use case. Algebrite.findDependenciesInScript("expression")[1] successfully returns a JS expression that can be evaluated. The name of the function is not the greatest, but I'm not gonna complain. Thanks for maintaining and updating this library, it has helped me a great deal.
