### ISSUE TITLE
float(sin(2)) = 0

### ISSUE THREAD

**Issue by danielsvane** [davidedc/Algebrite#34]
There is some weird things going on with getting the floating point value of cos and sin, for example float(sin(2)) = 0. I tried to debug this, but the source is hard to read.

**Comment by davidedc** [comment]
aknowledged.
indeed very strange. I'll be on holiday for the next three weeks, will look into this afterwards.

**Comment by davidedc** [comment]
noting for future reference that float(sin(2.0)) gives the correct result. Most probably something broken in float() implementation.

**Comment by danielsvane** [comment]
Yeah it's only a problem with integer values.

Have a nice vacation, and thanks for all your work. This project made many of my own projects possible, managed to finish this a few days ago thanks to you: http://molecularorbitals.herokuapp.com/

**Comment by davidedc** [comment]
fantastic, I'll link it from the Algebrite home page!

**Comment by davidedc** [comment]
fixed in 0.4.2 release notes here: file:///Users/daviddellacasa/Algebrite-website/docs/index.html
