### ISSUE TITLE
incorrect simplification of: sqrt(x*y) , sqrt(1/x) , sqrt(x^y)

### ISSUE THREAD

**Issue by sangwinc** [davidedc/Algebrite#35]
```simplify(sqrt(x*y))``` gives ```x^(1/2) y^(1/2)``` (incorrect: counterexample x = -1 and y = -1)
```simplify(sqrt(1/x))``` gives ```1 / x^(1/2)``` (incorrect: counterexample x = -1)
```simplify(sqrt(x^y))``` gives ```x^(1/2 y)``` (incorrect: counterexample x = -1)

the last case includes the example: ```simplify(sqrt(x^2))``` which gives ```x``` instead of ```abs(x)```

see https://en.wikipedia.org/wiki/Square_root#Principal_square_root_of_a_complex_number

**Comment by davidedc** [comment]
acknowledged. Needs fixing.

**Comment by sangwinc** [comment]
David,
Sorry if you've seen this already:  http://www.math.unm.edu/~wester/cas/book/Wester.pdf 
While not all of these will be relevant to algebrite (yet) it contains a very useful collection of test cases!  A number of other CAS used this collection, so I'm sure you can find a sensible machine readable version somewhere.
Chris

**Comment by davidedc** [comment]
Hi Chris, thanks for sending, yes I'm aware of the literature on limitations and "classic pitfalls" of CAS, including this paper.

I don't think that Algebrite can withstand any of the critiques of this paper, I'm concerned with more basic aspects for the time being (some tracked in here as Github issues, most of them tracked in personal notes), but I'll take a second look to see if there are tests that do pass!

**Comment by davidedc** [comment]
fixed in 0.4.2 release notes here: file:///Users/daviddellacasa/Algebrite-website/docs/index.html
