### ISSUE TITLE
wrong LaTeX output for exponentials (e.g.  x^11)

### ISSUE THREAD

**Issue by bloc97** [davidedc/Algebrite#40]
Algebrite.run("d(x^12, x)",true);
gives:
["12 x^11", "$$12x^11$$"]

This, displayed in LaTeX will show up as 12x^1  1,
$$12x^11$$
![Wrong output](https://latex.codecogs.com/png.latex?$$12x^11$$)

The correct output should be:
$$12x^{11}$$
![Correct output](https://latex.codecogs.com/png.latex?$$12x^{11}$$)

**Comment by bloc97** [comment]
If someone else also has this problem, this quick hack can work, although I don't know if it will break some other expressions.
Use the function fixLatex() on the TeX part of the Algebrite output.

`
const isLetter = function(char) {
    return char.toLowerCase() !== char.toUpperCase();
};

const isNumber = function(char) {
    return +char === +char;
};
const findNextDifferentChar = function(str, index) { //find the next dissimilar character
    if (isNumber(str[index])) { //if character is a number, return next character that isn't a number
        for (let i=index; i<str.length; i++) {
            if (!isNumber(str[i])) {
                return i;
            }
        }
        return str.length;
    } else if (isLetter(str[index])) { //if character is a letter, return next character that isn't a letter
        for (let i=index; i<str.length; i++) {
            if (!isLetter(str[i])) {
                return i;
            }
        }
        return str.length;
        
    } else { //if character is a parenthesis or a symbol, return the end index
        return str.length;
    }
};
const fixLatex = function(str) {
    
    let textPart = [];
    let lastindex = 0;
    
    for (let i=0; i<str.length-1; i++) {
        if (str[i] === "^") {
            const nextindex = findNextDifferentChar(str, i+1); //find next character that isn't similar to the one after the "^"
            textPart.push(str.slice(lastindex, i+1)); //push the unchanged part
            textPart.push("{" + str.slice(i+1, nextindex) + "}"); //push the exponent part in brackets
            lastindex = nextindex;
            i = nextindex-1; //skip the part already saved
        }
    }
    textPart.push(str.slice(lastindex, str.length)); //push in the last part that was not detected
    return textPart.join("");
};`

**Comment by davidedc** [comment]
acknowledged. Will examine the suggested fix. Should be more compact to fix the buggy code in the print routine inside but I'll check.

**Comment by davidedc** [comment]
fixed in 0.4.2 release notes here: http://algebrite.org/docs/index.html
