### ISSUE TITLE
wrong LaTeX output for multiplication

### ISSUE THREAD

**Issue by bloc97** [davidedc/Algebrite#42]
Algebrite.run("5^2 * 3^y", true)  
outputs:  
"$$253^y$$"  
![Wrong output](https://latex.codecogs.com/png.latex?$$253^y$$)

The correct output should be:  
"$$25\\cdot3^y$$"  
![Correct output](https://latex.codecogs.com/png.latex?$$25\cdot3^y$$)  

Originally found this problem when trying:  
float(sum(x,0,100, x*e^y))
Gives this TeX output: ![Wrong output](https://latex.codecogs.com/png.latex?$$5050.02.71828^y$$)

**Comment by bloc97** [comment]
This is unfortunately not fixable outside of Algebrite since there is no way to distinguish between the numbers.

**Comment by davidedc** [comment]
aknowledged

**Comment by davidedc** [comment]
so this one actually needs to be done case by case. In this case, where two numbers end up next to each other, then yes we need the cdot. In other cases we don't. So I'll carve-out this case first, we'll see which other cases we'll need to handle with the cdot, potentially we'll unify common scenarios if we see a pattern. I'm going to address this case specifically for the time being.

**Comment by davidedc** [comment]
fixed in v0.4.5 (both in master and in npm)
