### ISSUE TITLE
Parse to LaTeX without evaluation

### ISSUE THREAD

**Issue by gksander** [davidedc/Algebrite#43]
I'm trying to do the following: have an input box where a user can enter a string to be evaluated. When the user presses enter, the user's string will be parsed to LaTeX, followed by an equal sign, followed by the Algebrite evaluation of the string. (For example, if the user enters x*x then the output would be x \cdot x = x^2.)

The evaluated part is easy with the printlatex() function. I'm having trouble with the left-hand side of the equation. I'm currently using Alegbrite.run(\`printlatex(quote(${inp}))\`) which works well for many cases, but doesn't quite do what I'd expect in others. For example, entering [[1,2],[3,4]]^2 does not make the LHS of the equality a 2x2 matrix with a superscript-2. Is there a ready-made API function that I could use to essentially just parse a user input string without evaluating it first? (E.g., a sister to printlatex but without evaluation.)

**Comment by davidedc** [comment]
@gksander did you find what the issue was?

As an aside, I'm noticing now that ```printlatex(([[1,2],[3,4]]))``` gives much nicer latex output than ```printlatex(quote([[1,2],[3,4]]))``` ... they really should give the same latex... did you notice that as well?

**Comment by gksander** [comment]
I never found the issue. Using `printlatex(quote(...))` worked well for most things, but did strange things in other cases. I'll try to take a peak again soon and see if I can see what's going on, but I'm not super familiar with the core of Algebrite so it takes me awhile to chase down errors.

Yes -- the example you gave is exactly what I was running into. The `printlatex` does well, but it evaluates prior to outputting a TeX string which is good in most circumstances, but isn't great if you're trying to display using input in TeX form.
