### ISSUE TITLE
Matrix*Vector multiplication

### ISSUE THREAD

**Issue by CesMak** [davidedc/Algebrite#50]
A=[[0],[1]]
B=[[-4 / (-2 - 5 s + s^2) + s / (-2 - 5 s + s^2),2 / (-2 - 5 s + s^2)],[3 / (-2 - 5 s + s^2),-1 / (-2 - 5 s + s^2) + s / (-2 - 5 s + s^2)]]
B*A

Gives me:
[[0],[1]] [[-4 / (-2 - 5 s + s^2) + s / (-2 - 5 s + s^2),2 / (-2 - 5 s + s^2)],[3 / (-2 - 5 s + s^2),-1 / (-2 - 5 s + s^2) + s / (-2 - 5 s + s^2)]]

Actually this is NOT what I expected.....

I just tested this example on http://algebrite.org/#Matrices,%20tensors

Hope someone can help me - what do I wrong?

How to use Algebrite to multiplicate matrices and vectors?

A more simple example:
C=[[0,1]]
B=[[0],[1]]
C*B

[[0,1]] [[0],[1]]

**Comment by davidedc** [comment]
```*``` is the commutative multiplication, you want to use ```dot``` as in ```dot(C,B```).

The "shape" function will help you make sure you got the numbers of columns and rows right.

See https://github.com/davidedc/Algebrite/blob/master/tests/tensor.coffee#L14 for help on the rows/columns counting, and more in general these examples: https://github.com/davidedc/Algebrite/blob/master/tests/tensor.coffee and https://github.com/davidedc/Algebrite/blob/master/tests/transpose.coffee

**Comment by davidedc** [comment]
P.S. note that Algebrite can deal with "matrices" of dimension > 2, this is why the notation can be slightly odd, for example "shape" can reply a vector with more than two elements, and 1 is different from [1] which is different from [[1]] - because this more general notation will allow you to work with tensors in general.

**Comment by CesMak** [comment]
Thanks so much for that :)
