### ISSUE TITLE
How to do a 		partial fraction expansion ? 

### ISSUE THREAD

**Issue by CesMak** [davidedc/Algebrite#53]
Is it possible to do a partial fraction expansion with Algebrite?

e.g.:
2 / (394 - 50 s + s^2 ) = A/(s+s_1) + B/(s+s_2)

and A,B, s1, s2 should be calculated of course. 

Markus

**Comment by davidedc** [comment]
with "expand", see http://algebrite.org/docs/1.0.0/reference.html and https://github.com/davidedc/Algebrite/blob/150dfe8158c50d6abde9d2ec82d6ad7546182093/sources/expand.coffee . P.S. I don't think that your example has a partial fraction expansion.
