### ISSUE TITLE
limited precision floats

### ISSUE THREAD

**Issue by ribrdb** [davidedc/Algebrite#61]
1111 * 1111.0 = 1234320.0

In javascript the result is 1234321. What's going on here?

**Comment by davidedc** [comment]
this is terrible, thanks for bringing this up. I'll find the time to fix this somehow.

**Comment by davidedc** [comment]
apologies, I was mishandling the printout of the result. Fixed now.

**Comment by ribrdb** [comment]
Can you make a release with this fix?
