### ISSUE TITLE
Matrix multiplication and General Documentation

### ISSUE THREAD

**Issue by anurupmitra** [davidedc/Algebrite#64]
Hi,
I'm probably being very silly somewhere but I can't figure out how to multiply 2 matrices. I tried this :

```
Algebrite.run('A=[[a,b],[c,d]]');
Algebrite.run('C=[[x],[y]]');
Algebrite.run('A*C')
```

and got this:

`[[x],[y]] [[a,b],[c,d]]`

That looks like the two different matrices have been output?

Also, it would be super if the documentation could reflect the current version on Github!

Thanks and Regards
Anurup

**Comment by davidedc** [comment]
```dot(A,C)``` should do the trick. Can't use ```*``` because the engine considers ```*``` always to be commutative, which dot product isn't. (In fact, actually, in your result the order of the matrices is switched). Closing this issue for now, feel free to re-open if you find further issues.

**Comment by davidedc** [comment]
P.S. see this for more info: https://github.com/davidedc/Algebrite/blob/ec9b056a09fd2045a07516ed3b16ecd8a0ea07e7/sources/inner.coffee

**Comment by anurupmitra** [comment]
This is great! Thanks!
