### ISSUE TITLE
Algebrite home page: (x-1)(x-2)^3 should really be ((x-1)*(x-2))^3. Also check whether this example appears in tests.

### ISSUE THREAD

**Issue by samueltlg** [davidedc/Algebrite#68]
Hi there,

I have noticed on the Algebrite.org front-page that the expansion example '**(x-1)(x-2)^3**' returns -1. One has to insert an * symbol between (x-1) and (x-2) in order to produce the correct output.

Thanks,
Sam

**Comment by samueltlg** [comment]
Hi Davide,

Thank you for clearing that up. I guess I was just confused because the default example on algebrite.org had no multiplication symbol between bracketized expressions - '(x-1)(x-2)^3'.

Sam

**Comment by davidedc** [comment]
Actually, yes, I missed the point of your issue. Let me reopen it and rename it. Also (x-1)(x-2) should give some sort of meaningful error, I'm going to open another issue for that.

**Comment by davidedc** [comment]
corrected on the home page, now there is the "*" between the parentheses
