### ISSUE TITLE
default printout mode should be technically valid as input (in particular RE: explicit multiplication)

### ISSUE THREAD

**Issue by davidedc** [davidedc/Algebrite#73]
This came about after the thread in https://github.com/davidedc/Algebrite/issues/69 ( @pabloahb I think I changed my mind over this in respect to my comment there).

There is already a way to print-out in a "technical" representation that also makes sense as input i.e. ```printfull``` (mode ```PRINTMODE_FULL```), which is also the one used in the tests. So that's the one that should be default. The one that omits the products is ```printplain``` (i.e. mode ```PRINTMODE_PLAIN```) which is currently the default one in the environment.

So perhaps this is what should happen:
* the default print mode should be ```PRINTMODE_FULL```
* ```printplain``` and ```PRINTMODE_PLAIN``` should perhaps be renamed to  ```printhuman``` and ```PRINTMODE_HUMAN```
* the understanding should be that the only "technical" representation is ```printfull``` and mode ```PRINTMODE_FULL```. The other printouts (latex, "human", 2dascii and list) are not technically valid as input.

Any comments?

**Comment by pabloahb** [comment]
I think your solution is the best because that way you can use the results of algebrite in the input.

In fact, the real problem was that the input and the output had different syntaxes and that is solved with the use of "PRINTMODE_FULL"
