### ISSUE TITLE
More Unit Circle cases for arcsin/arccos?

### ISSUE THREAD

**Issue by aparkins** [davidedc/Algebrite#75]
```
simplify(arcsin(sqrt(2)/2))
> 1/4*pi
simplify(arcsin(1/2))
> 1/6*pi
simplify(arcsin(sqrt(3)/2))
> arcsin(1/2*3^(1/2))
```

It seems like arcsin and arccos don't handle pi/3 during simplification. A cursory glance through `arcsin.coffee` suggests this is just a unit circle value that was overlooked. It would be nice to see that added.

**Comment by dv-brianmickel** [comment]
Further cases:
- arcsin(sqrt(3)/2) -> Expected: pi/3, Actual: arcsin(1/2*3^(1/2))
- arcsin(-sqrt(3)/2) -> Expected: -pi/3, Actual: arcsin(-1/2*3^(1/2))
- arccos(sqrt(3)/2) -> Expected: pi/6, Actual: arccos(1/2*3^(1/2))
- arccos(-sqrt(3)/2) -> Expected: 5pi/6, Actual: arccos(-1/2*3^(1/2))

**Comment by davidedc** [comment]
the PR seems good, going to give it a second check tomorrow and merge

**Comment by davidedc** [comment]
merged. Thanks @aparkins, @dv-brianmickel
