### ISSUE TITLE
How do I evaluate this expression: 1+pi.

### ISSUE THREAD

**Issue by Kreijstal** [davidedc/Algebrite#79]
I like it that it doesn't instantly evaluate it, but if I want to evaluate it to arbitrary precision, how would I do it?

**Comment by davidedc** [comment]
Hi @Kreijstal . Algebrite supports numerical evaluation with standard floats (but no arbitrary precision yet).

You can use that in your example by either:

```float(1+pi)```

or

```1.0+pi``` (adding the decimal point to any number causes the whole expression to be numerically evaluated if possible)

**Comment by Kreijstal** [comment]
instead of implementing arbitrary precision into algebrite would you consider using something like mathjs, or are there no future plans to suppport it at all?

**Comment by davidedc** [comment]
https://github.com/MikeMcl/bignumber.js/ is smaller and would suffice. I'd know what to do, it'd just need a couple of weeks full time. It would be interesting to have, I just didn't get to it.
