### ISSUE TITLE
simplify doesn't simplify common factors in rational expressions

### ISSUE THREAD

**Issue by davidedc** [davidedc/Algebrite#89]
reported by @Frivolimous in https://github.com/davidedc/Algebrite/issues/88
example:
```simplify(x*(x+1)/(x+1)+1)``` gives ```(x^2+2*x+1)/(x+1)``` instead of ```x+1```

**Comment by davidedc** [comment]
simplify should determine if we are in the case of rational expressions and use some of the known techniques to simplify those.

e.g. this is close:

```
a = numerator(simplify(x*(x+1)/(x+1)+1))
b = denominator(simplify(x*(x+1)/(x+1)+1))
quotient(a,b)
> x+1
```

however note that this doesn't work in general because a) what happens if denominator is not fully included in the numerator? and b) quotient gives an answer also when the polynomials are not divisible (see quotient documentation) e.g.

```
quotient(x,x+1)
1
```

**Comment by davidedc** [comment]
also - we are leaving out of the discussion the fact that in theory we should track which constraints we are introducing as we simplify the rational expression, e.g. ```x/x = 1``` iff ```x != 0```.

**Comment by davidedc** [comment]
note that finding the gcd between the numerator and the denominator would help, as that can be simplified away. The trouble is that gcd between polynomials is hit and miss, for example this is wrong:

```
gcd((x+1)*(x+1),x+1)
> 1
```

while for example this works:

```
gcd(factor((x+2)*(x+3)),factor((x+1)*(x+3)))
> x+3
```

It seems like having a better gcd in N would be a next step here (then having it to work over fields would also be nice).

**Comment by Frivolimous** [comment]
also important to note that when it is pre-expanded the same issue occurs:
`(x^2+x) / (x+1) + 1` should also, in theory, have the `(x+1) factored out in the numerator and canceled with the denominator.

**Comment by davidedc** [comment]
@Frivolimous I gave this one a shot - can now simplify all rational expressions I see in basic textbook exercises see https://github.com/davidedc/Algebrite/blob/master/tests/simplify.coffee#L415 . If you could please send me more tests (in any form) that would be extremely useful as I might keep refactoring this area in the coming days, so more tests would help. Also any problem please let me know.

**Comment by Frivolimous** [comment]
this one is still not working: 

`simplify((x*(x+1))/(x+1)+1)` becomes `(x^2+2*x+1)/(x+1)` instead of `x+1`

**Comment by davidedc** [comment]
check if you checked out the latest changes from the repo - I seem to be getting the right result
![image](https://user-images.githubusercontent.com/769568/57862486-539a7a80-77f0-11e9-94b3-6c13301b1ae9.png)

**Comment by davidedc** [comment]
but yeah I mean this is only on Master on github - it's not on website yes (I'd need to cut a new version, update docs, create example etc, I batch those things up)

**Comment by Frivolimous** [comment]
oops!  Yes, the updated build works 👍 my git pull didn't go through so i was on the older version.

I will do some more testing for you and see if I can find any more edge cases.  Thank you so much!
