### ISSUE TITLE
roots(2^x - y, y) hangs

### ISSUE THREAD

**Issue by antimatter15** [davidedc/Algebrite#9]
Enter "roots(2^x - y, y)" into the sandbox and it hangs. This doesn't occur in the desktop Eigenmath.

**Comment by davidedc** [comment]
good spot. Eigenmath returns the constant 0x80000000 to indicate that there is no integer at the top of the stack, and uses some shortcuts (e.g. assuming that on 32 bits machines that's a negative number, and others). In JS those shortcuts don't work. Added to the tests.
