### ISSUE TITLE
Finding roots with inequality constraints

### ISSUE THREAD

**Issue by jarble** [davidedc/Algebrite#94]
I tried to find the roots of a polynomial with an inequality constraint: `nroots(x^2-4,x>0)`.
But instead of giving the solutions, Algebrite gives an error: `Stop: nroots: polynomial?`

This constraint could also be written as `nroots(x^2-4, sqrt(x)/x=1)`, but Algebrite gives the same error here.

Is there another way to find the roots with constraints like this one?

**Comment by davidedc** [comment]
Hi - indeed the second argument of nroots only specifies the variable to solve for. If you want to add a constraint, then probably the best way is to first find the solutions via nroots, and then "filter" them through the test (you can subst the numerical roots into x and then use the "test" function on "x>0" for example).
