### ISSUE TITLE
Native BigInt issue with fractional coefficients latex printing

### ISSUE THREAD

**Issue by azaloga** [davidedc/Algebrite#95]
A continuation of [this bug](https://github.com/davidedc/Algebrite/issues/78), but for printing to Latex of variables with fractional coefficients. Here are some examples that give a clear picture:

```
var Algebrite = require("algebrite")
console.log(Algebrite.run("printlatex(1/2*x)"));
console.log(Algebrite.quote("1/2*x").toLatexString());
```

Culprit appears to be the `Math.abs(...)` in `isNumberOneOverSomething` (see [runkit](https://npm.runkit.com/) stack trace of second example). 

Trying to find the cause of that was one nice headache on my end...ha. Thanks for the wonderful library.

**Comment by davidedc** [comment]
thanks will look into is.

link to runkit example: https://runkit.com/embed/7dfv3ox33dcc

**Comment by azaloga** [comment]
Looking into it some more, it seems that [this commit](https://github.com/davidedc/Algebrite/commit/e990414fa25c927bc8539b24e5683561d78d2b7b) fixes exactly this (and more, I assume). It is just unfortunately ahead of the current version that's on npm; not sure if it's enough of a reason to bump up the version on npm, but I know at least one person who would appreciate it greatly :D

**Comment by davidedc** [comment]
this is now done for you at latest version 1.3.0 see https://runkit.com/embed/wgvm33h43bt6

**Comment by azaloga** [comment]
Oh wow, thank you! Hope it was enough of a reason to bump up the version (I was more hopeful than serious in my last comment - I started pulling from the github repo rather than npm as soon as I found that commit).
